In [63]:
import pandas as pd

In [64]:
df = pd.read_csv(r"C:\Users\Ahmed tags\Desktop\CPC152\Data set 1 (12 KB) - heart_disease.csv")

In [84]:
#renameing some of the data columns because some of them are not understandable
df.rename(columns={
    'cp': 'ChestPainType',
    'trestbps': 'RestingBP',
    'chol': 'Cholesterol',
    'fbs': 'FastingBS',
    'thalach': 'MaxHR',
    'exang': 'ExerciseAngina',
    'ca': 'MajorVessels',
    'thal': 'Thalassemia',
}, inplace=True)

In [89]:
#as we can see the data is already cleaned.
df.isnull().sum()

age               0
sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
restecg           0
MaxHR             0
ExerciseAngina    0
oldpeak           0
slope             0
MajorVessels      0
Thalassemia       0
target            0
dtype: int64

In [67]:
#cheaking if there is a missing data
df.isnull().any()

age               False
sex               False
ChestPainType     False
RestingBP         False
Cholesterol       False
FastingBS         False
restecg           False
MaxHR             False
ExerciseAngina    False
oldpeak           False
slope             False
MajorVessels      False
Thalassemia       False
target            False
dtype: bool

______________________________________________________________

In [68]:
#removeing duplicated data
df.duplicated().sum()

1

In [69]:
df.drop_duplicates(inplace=True)

In [70]:

df.duplicated().sum()

0

In [107]:
# checking if there is a duplicated data
df.duplicated().any()

False

______________________________________________________________________________________________________________________________________________________

In [72]:
df

,age,sex,ChestPainType,RestingBP,Cholesterol,FastingBS,restecg,MaxHR,ExerciseAngina,oldpeak,slope,MajorVessels,Thalassemia,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [73]:
df.head()

,age,sex,ChestPainType,RestingBP,Cholesterol,FastingBS,restecg,MaxHR,ExerciseAngina,oldpeak,slope,MajorVessels,Thalassemia,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [74]:
df.tail()

,age,sex,ChestPainType,RestingBP,Cholesterol,FastingBS,restecg,MaxHR,ExerciseAngina,oldpeak,slope,MajorVessels,Thalassemia,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [75]:
df.sample()

,age,sex,ChestPainType,RestingBP,Cholesterol,FastingBS,restecg,MaxHR,ExerciseAngina,oldpeak,slope,MajorVessels,Thalassemia,target
262,53,1,0,123,282,0,1,95,1,2.0,1,2,3,0

_____________________________________________________________________________________________________________________________________________________

In [87]:
#showing the shape and the columns of the dataset
df.shape

(302, 14)

In [77]:
df.columns

Index(['age', 'sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'restecg', 'MaxHR', 'ExerciseAngina', 'oldpeak', 'slope',
       'MajorVessels', 'Thalassemia', 'target'],
      dtype='object')

______________________________________________________________________________________________________________________________________________________

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 302
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             302 non-null    int64
 1   sex             302 non-null    int64
 2   ChestPainType   302 non-null    int64
 3   RestingBP       302 non-null    int64
 4   Cholesterol     302 non-null    int64
 5   FastingBS       302 non-null    int64
 6   restecg         302 non-null    int64
 7   MaxHR           302 non-null    int64
 8   ExerciseAngina  302 non-null    int64
 9   oldpeak         302 non-null    float64
 10  slope           302 non-null    int64
 11  MajorVessels    302 non-null    int64
 12  Thalassemia     302 non-null    int64
 13  target          302 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 35.4 KB

In [79]:
df.dtypes

age                 int64
sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol         int64
FastingBS           int64
restecg             int64
MaxHR               int64
ExerciseAngina      int64
oldpeak           float64
slope               int64
MajorVessels        int64
Thalassemia         int64
target              int64
dtype: object

In [91]:
df['age'].describe()

count    302.00000
mean      54.42053
std        9.04797
min       29.00000
25%       48.00000
50%       55.50000
75%       61.00000
max       77.00000
Name: age, dtype: float64

In [93]:
 df.age.nunique()

41

In [94]:
df.age.unique()

array([63, 37, 41, 56, 57, 44, 52, 54, 48, 49, 64, 58, 50, 66, 43, 69, 59,
       42, 61, 40, 71, 51, 65, 53, 46, 45, 39, 47, 62, 34, 35, 29, 55, 60,
       67, 68, 74, 76, 70, 38, 77], dtype=int64)

In [95]:
df.columns

Index(['age', 'sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'restecg', 'MaxHR', 'ExerciseAngina', 'oldpeak', 'slope',
       'MajorVessels', 'Thalassemia', 'target'],
      dtype='object')

In [97]:
df.ChestPainType.nunique()

4

In [98]:
df.ChestPainType.unique()

array([3, 2, 1, 0], dtype=int64)

In [99]:
df.RestingBP.nunique()

49

In [101]:
df.RestingBP.unique()

array([145, 130, 120, 140, 172, 150, 110, 135, 160, 105, 125, 142, 155,
       104, 138, 128, 108, 134, 122, 115, 118, 100, 124,  94, 112, 102,
       152, 101, 132, 148, 178, 129, 180, 136, 126, 106, 156, 170, 146,
       117, 200, 165, 174, 192, 144, 123, 154, 114, 164], dtype=int64)

In [104]:
df.MaxHR.nunique()

91

In [106]:
df.MaxHR.unique()

array([150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 160, 139, 171,
       144, 158, 114, 151, 161, 179, 137, 157, 123, 152, 168, 140, 188,
       125, 170, 165, 142, 180, 143, 182, 156, 115, 149, 146, 175, 186,
       185, 159, 130, 190, 132, 147, 154, 202, 166, 164, 184, 122, 169,
       138, 111, 145, 194, 131, 133, 155, 167, 192, 121,  96, 126, 105,
       181, 116, 108, 129, 120, 112, 128, 109, 113,  99, 177, 141, 136,
        97, 127, 103, 124,  88, 195, 106,  95, 117,  71, 118, 134,  90],
      dtype=int64)